name: full-mocks
description: All services mocked for offline development
env:
  NODE_ENV: development
  USE_MOCKS: "true"
  MOCK_BEDROCK: "true"
  MOCK_DYNAMODB: "true"
  MOCK_S3: "true"
  MOCK_EXTERNAL_APIS: "true"
mocks:
  enabled: true
  services:
    - bedrock
    - dynamodb
    - s3
    - external