AWSTemplateFormatVersion: '2010-09-09'
Description: 'T-Developer MVP Simple S3 Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: development
  
  ProjectName:
    Type: String
    Default: t-developer-mvp

Resources:
  # S3 Bucket for generated projects (private)
  ProjectsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-projects-${Environment}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldProjects
            Status: Enabled
            ExpirationInDays: 7
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # S3 Bucket for static assets (public)
  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-assets-${Environment}-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  ProjectsBucketName:
    Description: Name of the projects S3 bucket
    Value: !Ref ProjectsBucket
    Export:
      Name: !Sub "${AWS::StackName}-projects-bucket"
  
  AssetsBucketName:
    Description: Name of the assets S3 bucket
    Value: !Ref AssetsBucket
    Export:
      Name: !Sub "${AWS::StackName}-assets-bucket"