# Performance Baseline Metrics Definition
# Day 5: Monitoring & Logging Infrastructure
# Generated: 2024-11-18
# T-Developer Evolution System Performance Standards

# ===================================
# Core Constraints (Non-negotiable)
# ===================================
constraints:
  agent_instantiation:
    max_time_us: 3.0
    unit: microseconds
    severity: critical
    description: "Maximum time to instantiate an agent"

  agent_memory:
    max_size_kb: 6.5
    unit: kilobytes
    severity: critical
    description: "Maximum memory footprint per agent"

  ai_autonomy:
    min_percentage: 85
    unit: percent
    severity: high
    description: "Minimum AI autonomy level"

# ===================================
# Performance Baselines
# ===================================
baselines:
  # Evolution Engine Performance
  evolution_engine:
    cycle_duration_ms:
      p50: 500
      p95: 1000
      p99: 2000
      max: 5000
      unit: milliseconds

    fitness_improvement_rate:
      min: 0.001  # Per cycle
      target: 0.01
      optimal: 0.05
      unit: ratio

    population_size:
      min: 50
      default: 100
      max: 500
      unit: count

    mutation_rate:
      min: 0.01
      default: 0.1
      max: 0.3
      unit: ratio

  # Agent Performance
  agent_performance:
    instantiation_time_us:
      p50: 2.0
      p95: 2.5
      p99: 2.8
      max: 3.0  # Hard constraint
      unit: microseconds

    memory_usage_kb:
      p50: 5.0
      p95: 6.0
      p99: 6.3
      max: 6.5  # Hard constraint
      unit: kilobytes

    processing_time_ms:
      p50: 10
      p95: 50
      p99: 100
      max: 500
      unit: milliseconds

  # Database Performance
  database_performance:
    query_latency_ms:
      p50: 5
      p95: 20
      p99: 50
      max: 200
      unit: milliseconds

    connection_pool_size:
      min: 10
      default: 50
      max: 100
      unit: connections

    transaction_rate:
      min: 100
      target: 1000
      max: 5000
      unit: tps  # transactions per second

  # Cache Performance
  cache_performance:
    hit_ratio:
      min: 0.7
      target: 0.9
      optimal: 0.95
      unit: ratio

    response_time_ms:
      p50: 1
      p95: 5
      p99: 10
      max: 50
      unit: milliseconds

    memory_usage_percent:
      warning: 80
      critical: 90
      max: 95
      unit: percent

  # API Performance
  api_performance:
    response_time_ms:
      p50: 50
      p95: 200
      p99: 500
      max: 2000
      unit: milliseconds

    throughput_rps:
      min: 100
      target: 1000
      max: 5000
      unit: requests_per_second

    error_rate:
      warning: 0.01  # 1%
      critical: 0.05  # 5%
      max: 0.1  # 10%
      unit: ratio

  # Safety System
  safety_system:
    check_latency_ms:
      p50: 10
      p95: 50
      p99: 100
      max: 500
      unit: milliseconds

    violation_response_time_ms:
      max: 100  # Must respond quickly
      unit: milliseconds

    false_positive_rate:
      max: 0.01  # 1%
      unit: ratio

    coverage:
      min: 0.99  # 99% coverage
      unit: ratio

# ===================================
# Alert Thresholds
# ===================================
alert_thresholds:
  # Critical Alerts (immediate action)
  critical:
    - metric: agent_instantiation_time
      condition: ">"
      value: 3.0
      unit: microseconds
      action: emergency_stop

    - metric: agent_memory_usage
      condition: ">"
      value: 6.5
      unit: kilobytes
      action: quarantine_agent

    - metric: safety_violations
      condition: ">"
      value: 0
      unit: count
      action: safety_review

    - metric: ai_autonomy_level
      condition: "<"
      value: 0.85
      unit: ratio
      action: increase_automation

  # High Priority Alerts
  high:
    - metric: error_rate
      condition: ">"
      value: 0.05
      unit: ratio
      duration: 5m

    - metric: database_cpu
      condition: ">"
      value: 80
      unit: percent
      duration: 10m

    - metric: cache_hit_ratio
      condition: "<"
      value: 0.7
      unit: ratio
      duration: 15m

  # Warning Alerts
  warning:
    - metric: memory_usage
      condition: ">"
      value: 80
      unit: percent
      duration: 30m

    - metric: disk_usage
      condition: ">"
      value: 70
      unit: percent
      duration: 1h

    - metric: api_latency_p95
      condition: ">"
      value: 500
      unit: milliseconds
      duration: 10m

# ===================================
# Health Score Calculation
# ===================================
health_score:
  weights:
    constraint_compliance: 0.4  # Most important
    performance_metrics: 0.3
    error_rates: 0.2
    resource_utilization: 0.1

  components:
    constraint_compliance:
      - instantiation_time_compliance
      - memory_usage_compliance
      - autonomy_level_compliance

    performance_metrics:
      - api_response_time
      - database_latency
      - cache_performance

    error_rates:
      - api_error_rate
      - evolution_error_rate
      - safety_violation_rate

    resource_utilization:
      - cpu_usage
      - memory_usage
      - disk_usage
      - network_usage

  scoring:
    excellent: ">= 0.95"
    good: ">= 0.85"
    acceptable: ">= 0.75"
    warning: ">= 0.60"
    critical: "< 0.60"

# ===================================
# Monitoring Intervals
# ===================================
monitoring_intervals:
  real_time:  # Sub-second monitoring
    - agent_instantiation_time
    - safety_violations
    - emergency_stops

  high_frequency:  # Every 10 seconds
    - api_response_time
    - cache_hit_ratio
    - active_connections

  standard:  # Every 30 seconds
    - cpu_usage
    - memory_usage
    - evolution_cycles
    - fitness_scores

  low_frequency:  # Every 5 minutes
    - disk_usage
    - backup_status
    - cost_metrics

  daily:  # Once per day
    - total_agents_created
    - evolution_progress
    - cost_analysis
    - security_audit

# ===================================
# Data Retention Policies
# ===================================
retention_policies:
  raw_metrics:
    high_resolution: 24h    # 1-second resolution
    medium_resolution: 7d   # 1-minute resolution
    low_resolution: 30d     # 5-minute resolution
    aggregated: 365d        # Daily aggregates

  logs:
    critical: 90d
    error: 30d
    warning: 14d
    info: 7d
    debug: 1d

  traces:
    complete: 24h
    sampled: 7d
    critical: 30d

  alerts:
    active: indefinite
    resolved: 90d

# ===================================
# SLOs (Service Level Objectives)
# ===================================
slos:
  availability:
    target: 99.9  # Three nines
    measurement_window: 30d

  latency:
    p50_target: 50ms
    p95_target: 200ms
    p99_target: 500ms
    measurement_window: 1h

  error_rate:
    target: 0.01  # 1%
    measurement_window: 1h

  constraint_compliance:
    instantiation_time: 100  # Must always comply
    memory_usage: 100        # Must always comply
    ai_autonomy: 99.9        # Nearly always comply
