---
# T-Developer Security Baseline Configuration
# Version: 1.0.0
# Date: 2024-12-08

aws_config:
  cloudtrail:
    enabled: true
    trail_name: t-developer-audit-trail
    s3_bucket: t-developer-cloudtrail-logs
    include_global_events: true
    enable_log_file_validation: true
    event_selectors:
      - read_write_type: All
        include_management_events: true
        data_resources:
          - type: AWS::S3::Object
            values: ["arn:aws:s3:::t-developer-*/*"]
          - type: AWS::RDS::DBCluster
            values: ["arn:aws:rds:*:*:cluster:t-developer-*"]

  guardduty:
    enabled: true
    finding_publishing_frequency: FIFTEEN_MINUTES

  security_hub:
    enabled: true
    standards:
      - AWS Foundational Security Best Practices
      - CIS AWS Foundations Benchmark
      - PCI DSS

iam_policies:
  password_policy:
    minimum_password_length: 14
    require_symbols: true
    require_numbers: true
    require_uppercase_characters: true
    require_lowercase_characters: true
    allow_users_to_change_password: true
    expire_passwords: true
    max_password_age: 90
    password_reuse_prevention: 24
    hard_expiry: false

  mfa_enforcement:
    required_for:
      - console_access: true
      - api_access: true
      - privileged_operations: true
    exemptions:
      - service_accounts
      - ci_cd_roles

  session_policy:
    max_session_duration: 3600  # 1 hour
    require_mfa_for_role_assumption: true

network_security:
  vpc_flow_logs:
    enabled: true
    traffic_type: ALL
    destination: s3

  security_groups:
    default_rules:
      - deny_all_inbound: true
      - allow_required_only: true
      - log_denied_connections: true

  network_acls:
    deny_known_bad_ips: true
    rate_limiting: true

data_protection:
  encryption:
    at_rest:
      s3:
        default_encryption: AES256
        bucket_key_enabled: true
      rds:
        encrypted: true
        kms_key_id: alias/t-developer-rds
      ebs:
        encrypted: true
        kms_key_id: alias/t-developer-ebs

    in_transit:
      enforce_tls: true
      minimum_tls_version: "1.2"

  backup:
    enabled: true
    retention_days: 30
    cross_region_backup: true

  data_loss_prevention:
    enabled: true
    sensitive_data_discovery: true
    alert_on_exposure: true

monitoring_and_alerting:
  cloudwatch_alarms:
    - name: UnauthorizedAPICallsAlarm
      metric: UnauthorizedAPICalls
      threshold: 5
      period: 300

    - name: RootAccountUsageAlarm
      metric: RootAccountUsage
      threshold: 1
      period: 60

    - name: IAMPolicyChangesAlarm
      metric: IAMPolicyEventCount
      threshold: 1
      period: 300

    - name: NetworkGatewayChangesAlarm
      metric: NetworkGatewayEventCount
      threshold: 1
      period: 300

  sns_topics:
    security_alerts:
      name: t-developer-security-alerts
      subscriptions:
        - protocol: email
          endpoint: security@t-developer.com
        - protocol: sms
          endpoint: "+1234567890"

compliance:
  standards:
    - GDPR
    - HIPAA
    - SOC2
    - ISO27001

  audit_frequency: quarterly

  reports:
    - type: compliance_report
      frequency: monthly
    - type: security_assessment
      frequency: quarterly
    - type: penetration_test
      frequency: annually

incident_response:
  runbook_location: s3://t-developer-runbooks/incident-response/

  escalation_chain:
    - level: 1
      contact: oncall@t-developer.com
      response_time: 15_minutes

    - level: 2
      contact: security-team@t-developer.com
      response_time: 30_minutes

    - level: 3
      contact: ciso@t-developer.com
      response_time: 1_hour

  automated_responses:
    - trigger: suspicious_activity
      action: isolate_resource
    - trigger: data_exfiltration_attempt
      action: block_and_alert
    - trigger: privilege_escalation
      action: revoke_and_investigate
