# T-Developer Evolution System Parameter Store Hierarchy
# AI-DRIVEN-EVOLUTION.md Day 2 - Parameter Store Structure

version: "1.0"
description: "Hierarchical structure for AWS Systems Manager Parameter Store"

# Root namespace: /{project_name}/{environment}/
hierarchy:
  # Evolution Engine Configuration
  evolution:
    path: "/{project_name}/{environment}/evolution"
    parameters:
      engine:
        config:
          description: "Main evolution engine configuration"
          type: "SecureString"
          tier: "Standard"
          structure:
            ai_autonomy_level: 0.85  # 85% AI autonomy
            max_agent_memory_kb: 6.5  # 6.5KB per agent
            instantiation_target_us: 3.0  # 3Î¼s target
            evolution_enabled: true
            safety_threshold: 0.95
            mutation_rate: 0.01
            fitness_evaluation_interval: 300  # seconds

      genetics:
        population:
          description: "Genetic algorithm population settings"
          type: "SecureString"
          structure:
            population_size: 100
            elite_ratio: 0.1
            crossover_rate: 0.7
            mutation_probability: 0.1

      safety:
        constraints:
          description: "Evolution safety constraints"
          type: "SecureString"
          structure:
            max_memory_usage_mb: 1024
            max_cpu_cores: 4
            max_network_bandwidth_mbps: 100
            malicious_pattern_detection: true
            auto_rollback_enabled: true

  # Agent Configurations
  agents:
    path: "/{project_name}/{environment}/agents"
    parameters:
      nl_input:
        config:
          description: "Natural Language Input Agent"
          type: "SecureString"
          structure:
            max_input_length: 10000
            processing_timeout: 60
            retry_attempts: 3
            cache_enabled: true

      ui_selection:
        config:
          description: "UI Element Selection Agent"
          type: "SecureString"
          structure:
            element_timeout: 5
            screenshot_enabled: true
            max_retry: 3

      parser:
        config:
          description: "Code Parser Agent"
          type: "SecureString"
          structure:
            max_parse_depth: 10
            strict_mode: false
            supported_languages: ["python", "javascript", "typescript"]

      component_decision:
        config:
          description: "Component Decision Agent"
          type: "SecureString"
          structure:
            confidence_threshold: 0.8
            fallback_enabled: true
            decision_timeout: 30

      match_rate:
        config:
          description: "Match Rate Calculation Agent"
          type: "SecureString"
          structure:
            similarity_algorithm: "cosine"
            min_match_score: 0.7
            fuzzy_matching: true

      search:
        config:
          description: "Code Search Agent"
          type: "SecureString"
          structure:
            max_results: 100
            search_depth: 5
            include_external: false

      generation:
        config:
          description: "Code Generation Agent"
          type: "SecureString"
          structure:
            max_tokens: 4096
            temperature: 0.7
            top_p: 0.9
            frequency_penalty: 0.0

      assembly:
        config:
          description: "Code Assembly Agent"
          type: "SecureString"
          structure:
            optimization_enabled: true
            minification: false
            source_maps: true

      download:
        config:
          description: "Download Management Agent"
          type: "SecureString"
          structure:
            max_file_size_mb: 100
            allowed_extensions: [".py", ".js", ".ts", ".json"]
            virus_scan_enabled: true

  # Workflow Configurations
  workflows:
    path: "/{project_name}/{environment}/workflows"
    parameters:
      code_generation:
        chain:
          description: "Code generation workflow chain"
          type: "String"
          value: "nl_input,ui_selection,parser,component_decision,generation,assembly"

      bug_fixing:
        chain:
          description: "Bug fixing workflow chain"
          type: "String"
          value: "nl_input,parser,component_decision,generation"

      optimization:
        chain:
          description: "Code optimization workflow chain"
          type: "String"
          value: "parser,match_rate,generation,assembly"

  # System Configuration
  system:
    path: "/{project_name}/{environment}/system"
    parameters:
      monitoring:
        config:
          description: "System monitoring configuration"
          type: "SecureString"
          structure:
            metrics_enabled: true
            log_level: "INFO"
            health_check_interval: 30
            alert_thresholds:
              cpu_percent: 80
              memory_percent: 85
              error_rate: 0.05

      performance:
        limits:
          description: "Performance limits and quotas"
          type: "SecureString"
          structure:
            max_concurrent_agents: 10
            max_queue_size: 1000
            request_timeout: 300
            rate_limit_per_minute: 60

      database:
        pool:
          description: "Database connection pool settings"
          type: "SecureString"
          structure:
            min_connections: 2
            max_connections: 20
            connection_timeout: 30
            idle_timeout: 600

  # Feature Flags
  features:
    path: "/{project_name}/{environment}/features"
    parameters:
      evolution:
        enabled:
          type: "String"
          value: "true"

      auto_scaling:
        enabled:
          type: "String"
          value: "false"

      advanced_monitoring:
        enabled:
          type: "String"
          value: "true"

      cost_optimization:
        enabled:
          type: "String"
          value: "true"

  # Global Settings
  global:
    path: "/{project_name}/{environment}/global"
    parameters:
      config:
        description: "Global environment configuration"
        type: "SecureString"
        structure:
          region: "us-east-1"
          availability_zones: ["us-east-1a", "us-east-1b"]
          backup_enabled: true
          disaster_recovery: true
          compliance_mode: "HIPAA"

# Environment-specific overrides
environments:
  development:
    overrides:
      evolution.engine.config.ai_autonomy_level: 0.7
      evolution.engine.config.evolution_enabled: true
      system.monitoring.config.log_level: "DEBUG"
      features.auto_scaling.enabled: "false"

  staging:
    overrides:
      evolution.engine.config.ai_autonomy_level: 0.8
      evolution.engine.config.evolution_enabled: true
      system.monitoring.config.log_level: "INFO"
      features.auto_scaling.enabled: "true"

  production:
    overrides:
      evolution.engine.config.ai_autonomy_level: 0.85
      evolution.engine.config.evolution_enabled: true
      system.monitoring.config.log_level: "WARNING"
      features.auto_scaling.enabled: "true"
      global.config.disaster_recovery: true

# Access Control
access_control:
  read_roles:
    - "arn:aws:iam::*:role/t-developer-read-*"
    - "arn:aws:iam::*:role/t-developer-agent-*"

  write_roles:
    - "arn:aws:iam::*:role/t-developer-admin"
    - "arn:aws:iam::*:role/t-developer-evolution-engine"

  kms_key_id: "arn:aws:kms:${region}:${account_id}:key/${parameter_store_key_id}"

# Validation Rules
validation:
  required_parameters:
    - evolution.engine.config
    - system.monitoring.config
    - global.config

  value_constraints:
    evolution.engine.config.ai_autonomy_level:
      min: 0.0
      max: 1.0
    evolution.engine.config.max_agent_memory_kb:
      min: 1.0
      max: 10.0
    evolution.engine.config.instantiation_target_us:
      min: 1.0
      max: 10.0
