version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: t-developer-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: t-developer-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus/data:/prometheus

  statsd:
    image: graphiteapp/graphite-statsd
    container_name: t-developer-statsd
    ports:
      - "8125:8125/udp"
      - "8126:8126"
      - "2003:2003"
