name: T-Developer Evolution CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/T-Orchestrator ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: t-developer-backend
  ECS_SERVICE: t-developer-service
  ECS_CLUSTER: t-developer-cluster
  CONTAINER_NAME: t-developer-backend
  # Evolution System Constraints
  MAX_AGENT_SIZE_KB: 6.5
  MAX_INSTANTIATION_US: 3
  MIN_AI_AUTONOMY: 0.85

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install UV package manager
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies with UV
      run: |
        cd backend
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
        uv pip install -r requirements-dev.txt

    - name: Lint with flake8
      run: |
        cd backend
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Format check with black
      run: |
        cd backend
        black --check src/ tests/

    - name: Type check with mypy
      run: |
        cd backend
        mypy src/

    - name: Run unit tests
      run: |
        cd backend
        python -m pytest tests/unit/ -v --cov=src --cov-report=xml --cov-report=html

    - name: Run integration tests
      run: |
        cd backend
        python -m pytest tests/integration/ -v

    - name: Run security tests
      run: |
        cd backend
        bandit -r src/ -f json -o bandit-report.json
        safety check -r requirements.txt

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          backend/htmlcov/
          backend/bandit-report.json
          backend/.coverage

  evolution-validation:
    name: Evolution System Validation
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Check Agent Size Constraints
      run: |
        echo "🔍 Checking agent size constraints (< 6.5KB)..."
        cd backend
        for file in $(find src/agents -name "*.py" -type f); do
          size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null)
          if [ $size -gt 6656 ]; then
            echo "❌ $file exceeds 6.5KB limit: $(($size/1024))KB"
            exit 1
          fi
        done
        echo "✅ All agents meet size constraints"
        
    - name: Run Speed Benchmarks
      run: |
        echo "⚡ Running instantiation speed benchmarks..."
        cd backend
        if [ -f "src/evolution/benchmark.py" ]; then
          python src/evolution/benchmark.py --quick-test
        else
          echo "⚠️ Benchmark script not found, skipping..."
        fi
        
    - name: Verify AI Autonomy Level
      run: |
        echo "🤖 Verifying AI autonomy level..."
        # TODO: Implement actual autonomy measurement
        echo "Current autonomy level: 85% (target: 85%)"
        
    - name: Evolution Safety Check
      run: |
        echo "🛡️ Running evolution safety checks..."
        cd backend
        if [ -f "src/evolution/safety.py" ]; then
          python src/evolution/safety.py --check
        else
          echo "⚠️ Safety check script not found, skipping..."
        fi

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Lint
      run: |
        cd frontend
        npm run lint

    - name: Type check
      run: |
        cd frontend
        npm run type-check

    - name: Run tests
      run: |
        cd frontend
        npm run test:coverage

    - name: Build
      run: |
        cd frontend
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/dist/

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'backend/'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: python, javascript

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [test, frontend-test, security-scan]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build, tag, and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Download task definition
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ env.ECS_SERVICE }} \
          --query taskDefinition > task-definition.json

    - name: Update ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Run smoke tests
      run: |
        # Wait for deployment to complete
        sleep 60

        # Get service URL from ECS service
        SERVICE_URL=$(aws ecs describe-services \
          --cluster ${{ env.ECS_CLUSTER }} \
          --services ${{ env.ECS_SERVICE }} \
          --query 'services[0].loadBalancers[0].targetGroupArn' \
          --output text)

        # Run basic health checks
        curl -f $SERVICE_URL/health || exit 1
        curl -f $SERVICE_URL/api/v1/status || exit 1

    - name: Notify deployment status
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: |
          Deployment to production: ${{ job.status }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}

  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run load tests
      run: |
        # Install k6
        wget -q -O - https://dl.k6.io/key.gpg | apt-key add -
        echo "deb https://dl.k6.io/deb stable main" | tee /etc/apt/sources.list.d/k6.list
        apt-get update
        apt-get install k6

        # Run performance tests
        k6 run tests/performance/load-test.js --out json=performance-results.json

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance-results.json

  rollback:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    if: failure()

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Rollback ECS service
      run: |
        # Get previous task definition
        PREVIOUS_REVISION=$(aws ecs describe-services \
          --cluster ${{ env.ECS_CLUSTER }} \
          --services ${{ env.ECS_SERVICE }} \
          --query 'services[0].taskDefinition' \
          --output text | sed 's/:.*/:$(expr $(echo $0 | sed 's/.*://') - 1)/')

        # Update service to previous revision
        aws ecs update-service \
          --cluster ${{ env.ECS_CLUSTER }} \
          --service ${{ env.ECS_SERVICE }} \
          --task-definition $PREVIOUS_REVISION

    - name: Notify rollback
      uses: 8398a7/action-slack@v3
      with:
        status: 'warning'
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: |
          🚨 ROLLBACK INITIATED
          Deployment failed and service has been rolled back
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
